---
title: "Tidy Tuesday (04-20-2021) - Netflix"
author: "Tim Gordon"
date: "April 20, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
# library(ggpubr)
library(here)
library(ggthemes)
library(ggtext)
library(maps)
library(gganimate)
```

## Load data

```{r load}
netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')

```

## Analysis

```{r}
netflix_titles <- netflix_titles %>%
  mutate(genre = str_extract(listed_in, "[^,]+")) %>%
  mutate(genre = str_trim(str_replace(genre, "(TV|Movies)", ""))) 

# netflix_titles %>%
#   tidytext::unnest_tokens(word, genre) %>%
#   count(word, sort=TRUE) %>%
#   mutate(word = fct_reorder(word, n)) %>%
#   ggplot(aes(word, n)) +
#   geom_col(aes(fill="brickred"), show.legend=FALSE) +
#   coord_flip() +
#   theme(plot.title.position = "plot",
#         plot.caption.position = "plot",
#         plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
#         plot.caption = element_text(size=12)) +
#   labs(title="Netflix breakdown",
#        caption="Viz by Tim Gordon | Dataset from Kaggle",
#        x = "",
#        y="Words")  
  
netflix_titles %>% summary()

netflix_titles %>%
  mutate(duration = parse_number(duration)) %>%
  filter(type!="Movie") %>%
  # count(type, duration) %>%
  ggplot(aes(duration, fill="brickred")) +
  geom_histogram(aes(y=..density.., fill="brickred"), color="white", bins=15) +
  geom_density(fill="grey", alpha=.7, bins=15)

netflix_titles %>%
  mutate(duration = parse_number(duration)) %>%
  filter(type=="Movie") %>%
  # count(type, duration) %>%
  ggplot(aes(duration)) +
  geom_histogram(aes(y=..density.., fill="brickred"), color="white", bins=15) +
  geom_density(fill="grey", alpha=.7, bins=15)

netflix_titles %>%
  count(genre) %>%
  filter(genre != "") %>%
  mutate(genre = fct_reorder(genre, n)) %>%
  ggplot(aes(genre, n)) +
  geom_col(aes(fill="brickred"), show.legend=FALSE) +
  coord_flip() +
  theme(plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
        plot.caption = element_text(size=12)) +
  labs(title="Netflix Breakdown by Genre",
       caption="Viz by Tim Gordon | Dataset from Kaggle",
       x = "",
       y="Genre")  

netflix_titles %>%
  count(country) %>%
  # filter(country != "United States") %>%
  ggplot(aes(country, n)) +
  geom_col()
```



```{r}
post_offices %>%
  skimr::skim()

### Remove discountinued offices not possible
post_offices <- post_offices %>%
  filter(established >= 1800 & discontinued < 2021) %>%
  mutate(gnis_full_name = paste0(str_to_title(gnis_name), ", ", str_to_title(gnis_county))) %>%
  select(!c(id, orig_county)) %>%
  distinct()

post_offices %>%
  filter(gnis_name != "NA" & duration > 100) %>%
  group_by(gnis_state) %>%
  summarise(sum = sum(duration), 
            count = n()) %>%
  mutate(gnis_state = fct_reorder(gnis_state, count)) %>%
  ggplot(aes(x=count, y=gnis_state, fill="#DC143C")) +
  geom_col() +
  theme_grey() +
  theme(legend.position = "none",
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
        plot.caption = element_text(size=12)) +
  labs(title="States with Post Offices over 100 years old",
       caption="Viz by Tim Gordon | Dataset from Cameron Blevins & Richard W. Helbock",
       x = "",
       y="State")
```



