---
title: "Tidy Tuesday (03-09-2021) - Bechdel"
author: "Tim Gordon"
date: "March 9, 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(skimr)
library(ggplot2)
library(janitor)
library(ggpubr)
library(here)
library(ggthemes)
#theme_set(theme_grey())
```

## Load data for Bechdel

```{r}
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')


```

### Bechdel Dataset Preparations

```{r}
raw_bechdel <- raw_bechdel %>%
  filter(year >= 1970) 

movies %>%
  skim()

raw_bechdel %>%
  skim()

movies <- movies %>%
  mutate(imdb = str_remove(imdb, "tt"))

bechdel <- raw_bechdel %>%
  inner_join(movies)

bechdel %>% 
  skim()

bechdel <- bechdel %>%
  filter(!is.na(runtime))

bechdel <- bechdel %>%
  mutate(runtime = str_remove(runtime, " min"),
         runtime = str_remove(runtime, "N/A")) %>%
  mutate(runtime = parse_number(runtime),
         domgross = parse_number(domgross),
         intgross = parse_number(intgross),
         domgross_2013 = parse_number(domgross_2013),
         intgross_2013 = parse_number(intgross_2013)) %>%
  filter(!is.na(runtime))
```


### Exploratory Data Analysis of Bechdel Dataset

```{r}

bechdel %>% 
  mutate(decade = 10 * (year %/% 10)) %>%
  mutate(tot_gross = (domgross + intgross)) %>%
  ggplot(aes(budget, tot_gross, color=binary)) +
  geom_point(size=3) +
  geom_smooth(method="lm") +
  theme_hc() +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  labs(x="Budget",
       y="Unadjusted Total Gross",
       title="Movie bechdel test vs Movie performance", 
       subtitle = "Movies that performed well in theatres performed slightly better on the bechdel test")

here('03-09-2021', 'plots')
ggsave(here('03-09-2021', 'plots', 'unadjusted_growth.png'), width = 20, height=20, units="cm")

bechdel %>% 
  mutate(tot_gross_2013 = (domgross_2013 + intgross_2013)) %>%
  ggplot(aes(budget_2013, tot_gross_2013, color=binary)) +
  geom_point(size=3) +
  geom_smooth(method="lm") +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) 

bechdel %>% 
  mutate(decade = 10 * (year %/% 10)) %>%
  mutate(tot_gross_2013 = (domgross_2013 + intgross_2013)) %>%
  mutate(ratings = fct_lump_n(rated, 3)) %>%
  ggplot(aes(budget_2013, tot_gross_2013, color=binary)) +
  geom_jitter(size=3) +
  geom_smooth(method="lm") +
  theme_fivethirtyeight() +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma) +
  facet_grid(ratings ~ .) +
  labs(x="Budget (2013 adj)",
       y="Total_gross (2013 adj)",
       title = "Movie ratings bechdel perforamnce",
       subtitle ="Movies for a younger audience have slightly better bechdel scores.",
       caption = "Viz by Tim Gordon | Dataset from FiveThirtyEight")

ggsave(here('03-09-2021', 'plots', 'bechdel_adjusted_gross_ratings.png'), width = 20, height=20, units="cm")

bechdel %>%
  mutate(ratings = fct_lump_n(rated, 3)) %>%
  ggplot(aes(runtime, color=binary)) +
  geom_density() +
  facet_grid(ratings~.) + 
  theme_minimal() +
  theme(legend.position="bottom") +
  # scale_y_continuous(labels=scales::percent) +
  labs(x="",
       y="Density", 
       title="Runtime Distribution by Ratings",
       subtitle = "Movies for younger audiences have a slightly higher bechdel score distribution",
       caption = "Viz by Tim Gordon | Dataset from FiveThirtyEight")

ggsave(here('03-09-2021', 'plots', 'runtime_dist.png'), width = 20, height=20, units="cm")

### Compare new ratings versus old
bechdel %>%
  mutate(ratings = fct_lump_n(rated, 3)) %>%
  group_by(ratings) %>%
  count()

bechdel %>%
  group_by(rated) %>%
  count()
```


