---
title: "Tidy Tuesday (03-23-2021) - un"
author: "Tim Gordon"
date: "March 23, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
library(ggpubr)
library(here)
library(ggthemes)
library(ggtext)
```

## Load data for Bechdel

```{r load}
unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')
```

## Analysis of un issues

```{r prep}
df <- roll_calls %>%
  left_join(unvotes) %>%
  left_join(issues, by = "rcid") 

```


```{r eda}
df %>%
  mutate(year=lubridate::year(date)) %>%
  mutate(decade = 10 * (year %/% 10)) %>%
  filter(importantvote==1 & !is.na(issue)) %>%
  group_by(issue, vote, decade) %>%
  count() %>% 
  ggplot(aes(decade, n, fill=vote)) +
  geom_col() +
  scale_fill_manual(values=c("#ff8c00", "#b22222", "#228b22")) +
  facet_wrap(~issue) +
  theme_hc() +
  labs(x="",
       y="",
       title="Important votes on Key Issues since the 1980s",
       subtitle = "Many countries abstained from voting on key issue votes like Human Rights and the Palestine conflict",
       caption = "Data from Harvard's Dataverse | Viz by Tim Gordon")

ggsave(here('tidy_tuesdays', '03-23-2021', 'plots', 'important_votes_distribution.jpeg'), width = 20, height=20, units="cm")
```

```{r}
df %>%
  mutate(year=lubridate::year(date)) %>%
  mutate(decade = 10 * (year %/% 10)) %>%
  filter(importantvote==1 & !is.na(issue)) %>%
  group_by(issue, decade) %>%
  summarize(n_votes = n(),
            n_yes=sum(vote=="yes"),
            pct_yes = n_yes/n_votes)
```


