---
title: "Tidy Tuesday (02-09-2021) - US Census Data"
author: "Tim Gordon"
date: "February 9, 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(skimr)
library(ggplot2)
library(tidytext)
library(dplyr)
library(janitor)
```

## Load data for Plastic Pollution

```{r}
lifetime_earn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/lifetime_earn.csv')
student_debt <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/student_debt.csv')
retirement <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/retirement.csv')
home_owner <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/home_owner.csv')
race_wealth <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/race_wealth.csv')
income_time <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_time.csv')
income_limits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_limits.csv')
income_aggregate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_aggregate.csv')
income_distribution <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_distribution.csv')
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```

```{r}
income_time <- income_time %>%
  clean_names()
```

### Looking at income changes by Class over the years

```{r}
income_time %>%
  mutate(percentile = factor(percentile, levels= c('10th','50th', '90th')),
         income_family = round(income_family, 0)) %>%
  filter(year > 1990) %>%
  ggplot(aes(x=year, y=income_family, label=income_family, color=percentile)) +
  geom_line(size=2) +
  geom_point(data=subset(income_time, year %in% c(2000, 2006, 2008, 2012, 2016)), color='black', size=3) +
  geom_text(data=subset(income_time, year %in% c(2000, 2006, 2008, 2012, 2016)), position=position_dodge(width=1.2), vjust=-1.5) +
  scale_y_log10() +
  labs(x='Year',
       y='Income',
       title='Income changes by Class',
       subtitle = 'Income was highest in 2000. The lowest percentile never recovered while the highest percentile expanded their wealth during the new century')
```

### Further analysis into this centuries income levels.

### Lower 10th percentile family income dropped by 14%. 
### 50 percentile barely made even, while the top 90th increased income by nearly 10%.

```{r}
income_time %>%
  filter(year %in% c(2000, 2016)) %>%
  arrange(percentile) %>%
  mutate(century_cmp = lag(income_family)) %>%
  mutate(pct_change = ((income_family-century_cmp)/income_family) * 100) %>%
  filter(year == 2016) 
```

```{r}

```

