---
title: "Tidy Tuesday (06-01-2021) - Survivor Show"
author: "Tim Gordon"
date: "June 1, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidytext)
library(here)
library(ggthemes)
library(ggtext)
```

## Load data

```{r load}
summary <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv')

```

## Analysis

```{r}
str(summary)

summary <- summary %>%
  separate(final_vote, c("first", "second", "third")) 

summary %>% mutate_if(is.character, as.numeric)

summary %>% 
  mutate_if(is.character, as.numeric) %>%
  arrange(season) %>%
  ggplot(aes(x=season, y=viewers_finale, size=first)) +
  geom_point() + 
  geom_smooth(stats="lm", se=FALSE)
```



```{r}
drivers %>%
  ggplot(aes(x=records, fill=nation)) +
  geom_histogram(bins=20)

drivers %>%
  # filter(position <= 10) %>%
  filter(!nation %in% c("Australia", "Brazil", "Canada"), !is.na(nation)) %>%
  mutate(area = case_when(
    nation == "USA" ~ "USA",
    TRUE            ~ "Europe"
  )) %>%
  group_by(area) %>%
  summarise(winners=sum(records))

summary(drivers$records)

drivers %>%
  # filter(position <= 10) %>%
  filter(!nation %in% c("Australia", "Brazil", "Canada"), !is.na(nation)) %>%
  mutate(area = case_when(
    nation == "USA" ~ "USA",
    TRUE            ~ "Europe"
  )) %>%
  ggplot(aes(x=year, y=records, color=area, fill=area)) + 
  geom_col(alpha=.3, position="dodge") +
  geom_smooth(stats="glm", se=FALSE) +
  scale_fill_manual(values= c("#003194", "#B90B2F")) +
  scale_color_manual(values= c("#003194", "#B90B2F")) +
  scale_y_log10() +
  labs(title="Mario Kart Records held by <span style = 'color:#B90B2F;'>USA</span> or <span style = 'color:#003194;'>EU</span> Players",
     subtitle= "<span style = 'color:#003194;'>EU</span> players consistenly held records throughout the years in Mario Kart N64.",
     caption="Viz by Tim Gordon | Dataset from Ask a Manager",
     x = "",
     y="Records Held") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(),
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
        plot.caption = element_text(size=12))
```








