---
title: "Tidy Tuesday (04-27-2021) - CEO"
author: "Tim Gordon"
date: "April 27, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidytext)
library(here)
library(ggthemes)
# library(ggtext)
```

## Load data

```{r load}
departures <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-27/departures.csv')

```

## Analysis

```{r}
departures %>% skimr::skim()
```


```{r}
departures %>%
  unnest_tokens(word, notes) %>%
  anti_join(stop_words) %>%
  count(word, sort=TRUE) %>%
  slice_max(n, 100) %>%
  ggplot(aes(x= n, y= word)) +
  geom_col()



# netflix_titles %>%
#   mutate(duration = parse_number(duration)) %>%
#   filter(type=="Movie") %>%
#   # count(type, duration) %>%
#   ggplot(aes(duration)) +
#   geom_histogram(aes(y=..density.., fill="brickred"), color="white", bins=15) +
#   geom_density(fill="grey", alpha=.7, bins=15) +
#   theme_grey() +
#   theme(plot.title.position = "plot",
#         legend.position = "none",
#       plot.caption.position = "plot",
#       plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
#       plot.caption = element_text(size=12)) +
#   labs(title="Netflix Movie Runtimes",
#        caption="Viz by Tim Gordon | Dataset from Kaggle",
#        x = "",
#        y="") 


```





