---
title: "Tidy Tuesday (06-01-2021) - Survivor Show"
author: "Tim Gordon"
date: "June 1, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidytext)
library(here)
library(ggthemes)
library(ggtext)
```

## Load data

```{r load}
summary <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv')

```

## Analysis

```{r}
str(summary)

summary <- summary %>%
  separate(final_vote, c("first", "second", "third")) 

summary %>% mutate_if(is.character, as.numeric)

summary %>% 
  mutate_if(is.character, as.numeric) %>%
  arrange(season) %>%
  ggplot(aes(x=season, y=viewers_finale)) +
  geom_point(aes(size=first), color="#bf2424") + 
  geom_smooth(color="#0c527f",stats="glm", se=FALSE) + 
  theme_grey() + 
  scale_y_log10() +
  theme(legend.position = "bottom",
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
        plot.caption = element_text(size=12)) +
  labs(x=NULL,
       y=NULL,
       size="Winner Votes",
       title="The Decline of Survivor",
       subtitle="The winner is more likely to sweep the final vote as the show progresses. Viewers decline significantly over the seasons.",
       caption="Viz by Tim Gordon | Dataset from survivoR package") 
  
```








