---
title: "Tidy Tuesday (06-08-2021) - Great Lakes Fishing"
author: "Tim Gordon"
date: "June 8, 2021"
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(ggplot2)
library(janitor)
library(tidytext)
library(here)
library(ggthemes)
library(ggtext)
```

## Load data

```{r load}
fishing <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/fishing.csv')
stocked <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/stocked.csv')

```

## Analysis

```{r}
fishing %>%
  group_by(lake, year) %>%
  filter(year >= 1990, lake=="Huron") %>%
  mutate(decade = 10 * (year %/% 10)) %>%
  ggplot(aes(x=lake, y=grand_total, fill=lake)) +
  geom_boxplot() +
  facet_grid(cols=vars(decade)) +
  # geom_point() +
  # geom_line() +
  theme(legend.position = "bottom",
        plot.title.position = "plot",
        plot.caption.position = "plot",
        plot.margin = unit(c(.2,.10, .2, .10), "cm"), #top, right, bottom, left
        plot.caption = element_text(size=12)) +
  labs(x=NULL,
       y="Total observed catches",
       color="Lake",
       title="Fish totals declining",
       subtitle="Superior has largest change",
       caption="Viz by Tim Gordon | Dataset from Great Lakes Fishery Commission") 
```











