---
title: "Tidy Tuesday (02-02-2021) - College Enrollment"
author: "Tim Gordon"
date: "February 2, 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(skimr)
library(ggplot2)
library(tidytext)
library(dplyr)
library(janitor)
```

## Load data for Plastic Pollution

```{r}
college <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-02/hbcu_all.csv')
```

```{r}
college <- college %>%
  clean_names()
```

### Analysis of college enrollment

```{r}
college %>%
  ggplot(aes(x=year, y=total_enrollment)) +
  geom_line(size=2) +
  theme_bw() +
  labs(x="Year",
       y="Total Enrollments", 
       title="Total University Enrollments over time.",
       subtitle = "Steepest decline follows growth after 2010.")
```

### Plotting gender distribution in Enrollment

```{r}
plot1 <- college %>%
  select(year, males, females) %>%
  pivot_longer(males:females, names_to ="gender", values_to="values") %>%
  mutate(gender = factor(gender, levels = c('males', 'females'))) %>%
  ggplot(aes(year, values, color=gender)) +
  geom_line(size=2) 

plot1 + 
  geom_vline(xintercept=2010) +
  geom_text(x = 2002, y=200000, size=3.5, color='black', label='Both men and women returning to school after 2008') +
  labs(x='Year', 
       y='Enrollments',
       title='Gender enrollment over time',
       subtitle = 'Enrollment increased after 2008 recession. Downward trend following largest year in enrollments') +
  theme_bw()
```

### College programs enrollemnt rates

```{r program_enrollment}
college_programs <- college %>%
  select(year, contains(c("year_public", "year_private"))) %>%
  pivot_longer(cols=x4_year_public:x2_year_private, 
               names_pattern="[x_]?(.*)_(.*)",
               names_to =c("program","university_type"), values_to="students")
```

### College programs enrollment graphs

```{r program_graphs}
college_programs %>% 
  mutate(program = factor(program, levels = c("4_year", "2_year"))) %>%
  ggplot(aes(x=year, y=students, color=program)) +
  geom_line(size=2, alpha=.8) +
  facet_grid(university_type ~ .) + 
  labs(x="Year",
       y="Student Enrollment",
       title="Student Program Enrollment by University",
       subtitle = "Public schools saw increased growth over time while private schools stagnated.") +
  theme_bw()
```

