---
title: "Tidy Tuesday (01-26-2021) - Plastic Pollution"
author: "Tim Gordon"
date: "January 28, 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(skimr)
library(ggplot2)
library(tidytext)
library(dplyr)
```

## Load data for Plastic Pollution

```{r}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
```

### Analysis of plastic by country

```{r}
### remove grand total, make titles, and replace GB
plastics <- plastics %>%
  filter(parent_company != "Grand Total") %>%
  mutate(country = str_to_title(country)) %>%
  mutate(country = str_replace(country, "United Kingdom Of Great Britain & Northern Ireland$", "United Kingdom"))


### Update chart for correct order
plastics %>%
  filter(country != "Empty") %>% 
  group_by(country, year) %>%
  summarise(num_events = sum(num_events)) %>%
  ungroup() %>%
  mutate(year = factor(year, labels = c("2019", "2020"))) %>%
  #top_n(50) %>%
  ggplot(aes(num_events, reorder(country, num_events), fill=year)) +
  geom_col() + 
  labs(title="Events by Country",
       x="Number of Events", 
       y="Country") +
  theme_grey()
```

### Looking at change from 2019 to 2020 for plastic removal events by country

```{r plastics_change_country}
plastics %>%
  filter(country != "Empty") %>% 
  group_by(country, year) %>%
  summarise(num_events = sum(num_events), n= n()) %>%
  ungroup() %>%
  mutate(year = factor(year, labels = c("2019", "2020"))) %>%
  mutate( area = factor(ifelse(country %in% c("United States Of America",
                                              "Philippines", "Malaysia" ,"Japan",
                                              "India", "China"),"Highlighted","Normal"))) %>%
  ggplot(aes(year, num_events, group=country, alpha=area, color=country)) +
  geom_line(size=1.2) + 
  geom_text(aes(label= country)) +
  scale_y_log10() +
  scale_alpha_manual(name = "country", values=c(1, 0.15)) +
  labs(title="Events by Country 2019 vs 2020",
       subtitle = "Highlighted countries with changes over events hosted",
       x="Number of Events", 
       y="Country") +
  theme_grey() +
  theme(legend.position = "none")
```

### Looking at change from 2019 to 2020 for all plastic removed by country

```{r plastics_change_amount}
plastics %>%
  group_by(country, year) %>%
  summarise_at(vars(hdpe:num_events), sum, na.rm=TRUE) %>%
  ungroup() %>%
  mutate(year = factor(year, labels = c("2019", "2020"))) %>%
  mutate( area = factor(ifelse(country %in% c("Switzerland", "Nigeria", "Sri Lanka",
                                              "Philippines", "United Arab Emirates" ,"Japan",
                                              "India"),"Highlighted","Normal"))) %>%
  ggplot(aes(year, grand_total, group=country, alpha=area, color=country)) +
  geom_line(size=1.2) + 
  geom_text(aes(label= country)) +
  scale_y_log10() +
  scale_alpha_manual(name = "country", values=c(1, 0.15)) +
  labs(title="Total Plastic cleaned by Country 2019 vs 2020",
       subtitle = "Highlighted countries with changes over total plastic removal from 2019 to 2020",
       x="Total Number of Plastics", 
       y="Country") +
  theme_grey() +
  theme(legend.position = "none")
```

### Looking at data unassigned

```{r}
### Plastics with no country assigned 
plastics %>%
  filter(country == "Empty") %>%
  group_by(country) %>%
  summarise_at(vars(hdpe:grand_total), sum, na.rm=TRUE)
```

