---
title: "Tidy Tuesday (02-16-2021) - US Airlines Data"
author: "Tim Gordon"
date: "February 16, 2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache=TRUE, warning=FALSE,
                      message=FALSE, echo = TRUE, dpi=180,
                      fig.width = 9, fig.height = 6)
library(tidyverse)
library(skimr)
library(ggplot2)
library(tidytext)
library(data.table)
library(tidytable)
library(janitor)
library(ggpubr)
library(here)
library(ggthemes)
#theme_set(theme_grey())
```

## Load data for Airline

```{r}

df <- fread(file=here('02-16-2021', 'airline_delay_causes', 'airline_delay_causes.csv') )

df <- df %>%
  clean_names() 

df <- df %>%
  #select.(airport_name) %>%
  separate.(airport_name, into=c("loc", "name"), sep=":") %>%
  separate.(loc, into = c("city", "state"), sep=", ") %>%
  select.(-v22)

```

### Exploratory Data Analysis of Flight Data

```{r}
airlines_limited <- c("Delta Air Lines Inc.", "SkyWest Airlines Inc.", "ExpressJet Airlines Inc.", 
                      "United Air Lines Inc.","Southwest Airlines Co.", "American Airlines Inc.",
                      "Alaska Airlines Inc.")

top_airports <- c("ORD", "ATL", "LAX", "DFW", "DEN", "JFK")



df %>% 
  dt(year < 2020 & carrier_name %in% airlines_limited, .(carrier = mean(carrier_delay), weather = mean(weather_delay), nas=mean(nas_delay), diverted = mean(arr_diverted), late = mean(late_aircraft_delay)), by=.(year, month, carrier_name)) %>%
  pivot_longer.(!c(year, month, carrier_name), names_to="delay_type", values_to="amount") %>%
  mutate.(date = as.Date(paste(year, month, 01), "%Y %m %d")) %>%
  ggplot(aes(date, amount, color=delay_type)) +
  geom_line(size=1.3) +
  facet_grid(~carrier_name, scales="free_x") +
  #scale_x_date(label = date_format("%b"), date_breaks = "5 years") +
  theme_fivethirtyeight()+
  theme(legend.position="bottom") +
  labs(x="Date", 
       y="Avg Delays",
       title="Top 7 Airlines Avg Delays between 2004 & 2019")

  
df %>%
  select.(name, state, year) %>%
  mutate.(decade = 10 * (year %/% 10)) %>%
  count.(state, decade) %>%
  ggplot(aes(N, reorder(state,N))) +
  geom_col() +
  facet_wrap(~decade) +
  labs(x="Cases",
       y="State",
       title="Yearly Records")


df %>%
  select.(name, state, year) %>%
  mutate.(decade = 10 * (year %/% 10)) %>%
  count.(state, decade) %>% 
  mutate.(decade = as.factor(decade),
          state = as.factor(state)) %>%
  mutate.(state = fct_reorder(state, N)) %>%
  ggplot(aes(N, state, fill=decade)) +
  geom_col() +
  facet_wrap(~decade) +
  labs(x="Cases",
       y="State",
       title = "Cases across the decades for each state") +
  theme(legend.position = "none")

### Dallas/Fort Worth & Atlanta & Chicago O'Hare airport had the most delays out of the 6 biggest airports in the country. 
### It's interesting that DFW American Airlines and the most delays 

### Delta Airlines also had multiple delays at Atlanta.

df %>%
  select.(arr_flights, arr_delay, carrier_name, airport) %>%
  filter.(airport %in% top_airports & carrier_name %in% airlines_limited) %>%
  ggplot(aes(arr_flights, arr_delay, color=carrier_name)) +
  geom_point() +
  facet_wrap(~airport) +
  theme_hc() +
  scale_y_continuous(labels = scales::comma) +
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(nrow = 2)) +
  labs(x='Flights',
       y='Delays',
       title="Flights vs Delays",
       subtitle="Comparison between the most popular airports and carriers")

  
  
```

